package Movies;

public class MoviesArray {
    public static Movies[] findAll() {
        return new Movies[]{
                new Movies("Citizen Kane", "drama"),
                new Movies("Casablanca", "drama"),
                new Movies("The Godfather", "drama"),
                new Movies("Gone With The Wind", "drama"),
                new Movies("Lawrence Of Arabia", "drama"),
                new Movies("The Wizard Of Oz", "musical"),
                new Movies("The Graduate", "drama"),
                new Movies("On The Waterfront", "drama"),
                new Movies("Schindler's List", "drama"),
                new Movies("Singin' In The Rain", "musical"),
                new Movies("It's A Wonderful Life", "drama"),
                new Movies("Sunset Boulevard", "drama"),
                new Movies("The Bridge On The River Kwai", "drama"),
                new Movies("Some Like It Hot", "drama"),
                new Movies("Star Wars", "scifi"),
                new Movies("All About Eve", "drama"),
                new Movies("The African Queen", "drama"),
                new Movies("Psycho" , "horror"),
                new Movies("Chinatown", "drama"),
                new Movies("One Flew Over The Cuckoo's Nest", "drama"),
                new Movies("The Grapes Of Wrath", "drama"),
                new Movies("2001: A Space Odyssey", "scifi"),
                new Movies("The Maltese Falcon", "drama"),
                new Movies("Raging Bull", "drama"),
                new Movies("E.T. The extra-terrestrial", "scifi"),
                new Movies("Dr. Strangelove", "drama"),
                new Movies("Bonnie And Clyde", "drama"),
                new Movies("Apocalypse Now", "drama"),
                new Movies("Mr. Smith Goes to Washington", "drama"),
                new Movies("The Treasure Of The Sierra Madre", "drama"),
                new Movies("Annie Hall", "comedy"),
                new Movies("The Godfather Part II", "drama"),
                new Movies("High Noon", "drama"),
                new Movies("To Kill A Mockingbird", "drama"),
                new Movies("It Happened One Night", "drama"),
                new Movies("Midnight Cowboy", "drama"),
                new Movies("The Best Years Of Our Lives", "drama"),
                new Movies("Double Indemnity", "drama"),
                new Movies("Doctor Zhivago", "drama"),
                new Movies("North By Northwest", "drama"),
                new Movies("West Side Story", "musical"),
                new Movies("Rear Window", "drama"),
                new Movies("King Kong", "horror"),
                new Movies("The Birth Of A Nation", "drama"),
                new Movies("A Streetcar Named Desire", "drama"),
                new Movies("A Clockwork Orange", "scifi"),
                new Movies("Taxi Driver", "drama"),
                new Movies("Jaws", "horror"),
                new Movies("Snow White And The Seven Dwarfs", "animated"),
                new Movies("Butch Cassidy And The Sundance Kid", "drama"),
                new Movies("The Philadelphia Story", "drama"),
                new Movies("From Here To Eternity", "drama"),
                new Movies("Amadeus", "drama"),
                new Movies("All Quiet On The Western Front", "drama"),
                new Movies("The Sound Of Music", "musical"),
                new Movies("M*A*S*H", "comedy"),
                new Movies("The Third Man", "drama"),
                new Movies("Fantasia", "animated"),
                new Movies("Rebel Without A Cause", "drama"),
                new Movies("Raiders Of The Lost Ark", "drama"),
                new Movies("Vertigo", "drama"),
                new Movies("Tootsie", "comedy"),
                new Movies("Stagecoach", "drama"),
                new Movies("Close Encounters Of The Third Kind", "scifi"),
                new Movies("The Silence Of The Lambs", "horror"),
                new Movies("Network", "drama"),
                new Movies("The Manchurian Candidate", "drama"),
                new Movies("An American In Paris", "drama"),
                new Movies("Shane", "drama"),
                new Movies("The French Connection", "drama"),
                new Movies("Forrest Gump", "drama"),
                new Movies("Ben-Hur", "drama"),
                new Movies("Wuthering Heights", "drama"),
                new Movies("The Gold Rush", "drama"),
                new Movies("Dances With Wolves", "drama"),
                new Movies("City Lights", "drama"),
                new Movies("American Graffiti", "drama"),
                new Movies("Rocky", "drama"),
                new Movies("The Deer Hunter", "drama"),
                new Movies("The Wild Bunch", "drama"),
                new Movies("Modern Times", "drama"),
                new Movies("Giant", "drama"),
                new Movies("Platoon", "drama"),
                new Movies("Fargo", "drama"),
                new Movies("Duck Soup", "comedy"),
                new Movies("Mutiny On The Bounty", "drama"),
                new Movies("Frankenstein", "horror"),
                new Movies("Easy Rider", "drama"),
                new Movies("Patton", "drama"),
                new Movies("The Jazz Singer", "drama"),
                new Movies("My Fair Lady", "musical"),
                new Movies("A Place In The Sun", "drama"),
                new Movies("The Apartment", "drama"),
                new Movies("Goodfellas", "drama"),
                new Movies("Pulp Fiction", "drama"),
                new Movies("The Searchers", "drama"),
                new Movies("Bringing Up Baby", "drama"),
                new Movies("Unforgiven", "drama"),
                new Movies("Guess Who's Coming To Dinner", "drama"),
                new Movies("Yankee Doodle Dandy", "musical")
        };
    }
}